<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Save on pre-owned Amazon devices__fluid_e59185</name>
   <tag></tag>
   <elementGuidId>82cec391-f348-4464-ba02-eab4372319f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardInstanceaI4jySjT3ywDU0tjbk6z5A > a.a-link-normal._fluid-fat-image-link-v2_style_mergedLinks__10JqZ > div._fluid-fat-image-link-v2_style_fluidFatImageLinkBody__1LsOX > div.a-section.a-spacing-none._fluid-fat-image-link-v2_style_fluidImageContainer__2SOMr > img._fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK._fluid-fat-image-link-v2_style_fluidImage__gTBjA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceaI4jySjT3ywDU0tjbk6z5A']/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4f1737ee-9bc9-4772-9be7-93ab3a7b6952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Save on pre-owned Amazon devices</value>
      <webElementGuid>b1c1a40b-cdb3-4f8e-836a-6fe4c5e153a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/kindle/journeys/YjAwMjVmYjUt/YjAwMjVmYjUt-YmMzZGJjMzYt-w379._SY304_CB410321238_.jpg</value>
      <webElementGuid>8b594d4d-ea70-4d9e-b1da-69f9610876fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK _fluid-fat-image-link-v2_style_fluidImage__gTBjA</value>
      <webElementGuid>30515751-4df4-4199-9ab2-ca3b24078087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/kindle/journeys/YjAwMjVmYjUt/YjAwMjVmYjUt-YmMzZGJjMzYt-w758._SY608_CB410321238_.jpg</value>
      <webElementGuid>76e26a09-ef1d-48d6-a577-35adf0525760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceaI4jySjT3ywDU0tjbk6z5A&quot;)/a[@class=&quot;a-link-normal _fluid-fat-image-link-v2_style_mergedLinks__10JqZ&quot;]/div[@class=&quot;_fluid-fat-image-link-v2_style_fluidFatImageLinkBody__1LsOX&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-fat-image-link-v2_style_fluidImageContainer__2SOMr&quot;]/img[@class=&quot;_fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK _fluid-fat-image-link-v2_style_fluidImage__gTBjA&quot;]</value>
      <webElementGuid>a5ee23ab-b0d6-453d-a2bf-4c48e474eb07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceaI4jySjT3ywDU0tjbk6z5A']/a/div/div/img</value>
      <webElementGuid>230cce7a-6258-48a4-b462-1ef72d7a5087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Save on pre-owned Amazon devices']</value>
      <webElementGuid>a9034553-84b2-46c2-83a9-0d27ccb01ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/div/img</value>
      <webElementGuid>5aecc0f4-9d03-45ac-87fe-acda9db62ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Save on pre-owned Amazon devices' and @src = 'https://images-na.ssl-images-amazon.com/images/G/01/kindle/journeys/YjAwMjVmYjUt/YjAwMjVmYjUt-YmMzZGJjMzYt-w379._SY304_CB410321238_.jpg']</value>
      <webElementGuid>6ea42b8d-5e2f-4a5c-bcb8-95400e9513e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
