<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_LOGIN_006</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4bd2d8e7-6726-442c-9d65-86883d0a50f3</testSuiteGuid>
   <testCaseLink>
      <guid>f51aaec0-ebdc-4693-94d6-2062ee08d072</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven Testing/TC_LOGIN_006</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f65bf5e0-8b4a-45a1-84f5-7035f8d7c4dc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Datadriven/login_credentials</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac52a8e6-8361-442a-8947-21bf098ef997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85c4bfc9-532c-44fb-9477-a66e9c86576a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
