<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5</name>
   <tag></tag>
   <elementGuidId>323b6495-34a5-4af9-acdc-992ee4bd04c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='quantity_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a10faf89-010b-4f60-9ef3-cbeb6a677e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>36753457-37fd-4388-97a8-ced35836f3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>82c384a6-6914-485c-8b9b-f5603a502f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>103858b4-6ee2-4d32-91d4-5d5a7cffad63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;5&quot;}</value>
      <webElementGuid>4ada9522-0b60-48a2-b76b-8ee03f483654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_5</value>
      <webElementGuid>83f991dc-8031-41fe-96eb-f0ec7f0d00e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>8c6d54ac-fec4-4047-a051-bac706c47b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>47d7b22f-11fc-4b45-b1fc-3a3ea2639a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_5&quot;)</value>
      <webElementGuid>3635c3ed-c95b-4dac-a89b-4bdb95f03b81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='quantity_5']</value>
      <webElementGuid>890603bb-950c-4329-adae-693df70fab32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-3']/div/div/ul/li[6]/a</value>
      <webElementGuid>1796befe-a1a3-490a-bb18-1f92b7757071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'5')]</value>
      <webElementGuid>2ed6c8cb-5dba-4634-94c2-825aac7867ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[23]</value>
      <webElementGuid>fda44c31-7bff-4a7c-ac51-af11df3ce1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/ul/li[6]/a</value>
      <webElementGuid>ce8d6acd-62ff-4040-9d5c-0d191c2fea91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'quantity_5' and (text() = '5' or . = '5')]</value>
      <webElementGuid>3d9dcef1-9c29-46d4-8412-77fc08b7b319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
