<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_us</name>
   <tag></tag>
   <elementGuidId>a7c64083-d395-43b9-8a80-ec305b854bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-logo-sprites']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-logo-sprites</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1094fe03-4de4-428c-b0a5-886df56b52e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ref=nav_logo</value>
      <webElementGuid>8605ff51-1a6c-4483-9855-71128c9f4200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-logo-sprites</value>
      <webElementGuid>51c425ed-2ef9-4696-92d0-de5ac0752904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-logo-link nav-progressive-attribute</value>
      <webElementGuid>0867a4d0-524d-4c40-8c79-77e9dcf3eed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amazon</value>
      <webElementGuid>53d9e080-f2ae-43b9-a51d-c458c27beff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      
      
      .us
    </value>
      <webElementGuid>dbfedc59-c049-4e42-ab09-5140da72d2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-logo-sprites&quot;)</value>
      <webElementGuid>c7412d22-af91-4d30-a679-88473ccfa263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-logo-sprites']</value>
      <webElementGuid>b5992d34-ac0e-4eb0-9c54-494024199dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-logo']/a</value>
      <webElementGuid>eb120f23-ee9a-40b2-9760-2cb4ce999c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ref=nav_logo')]</value>
      <webElementGuid>49224cb2-1725-4221-8831-adfebc33ef17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>16bf7d94-9ad3-44fa-b84f-2f2a053e9bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ref=nav_logo' and @id = 'nav-logo-sprites' and (text() = '
      
      
      .us
    ' or . = '
      
      
      .us
    ')]</value>
      <webElementGuid>d9d44732-9bd4-4f70-8d08-4dc293200f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
