<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Quantity</name>
   <tag></tag>
   <elementGuidId>5c3d3ccb-1a4f-4922-a6a1-471641acd10a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.a-native-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectQuantity']/span/div/div/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a6b03788-36d2-4718-8dca-2ddfc831c073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>5ade62ca-ed88-4602-87f0-0165ae05292f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-native-dropdown</value>
      <webElementGuid>5b482561-f04f-4c09-ad2f-3845bc5347a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quantity:</value>
      <webElementGuid>6e1e35d8-dee5-452b-a45e-0d6ff4c32c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectQuantity&quot;)/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;a-row a-spacing-base&quot;]/div[@class=&quot;a-column a-span12 a-text-left&quot;]/span[@class=&quot;a-dropdown-container&quot;]/label[@class=&quot;a-native-dropdown&quot;]</value>
      <webElementGuid>426dba2b-5ba5-4d8f-bc8e-3a11904dbcc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectQuantity']/span/div/div/span/label</value>
      <webElementGuid>110dfabc-f3ea-4fcc-9208-ed8c9522e1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>62ef6009-c363-4545-9f0d-5f7553bb9cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Quantity:' or . = 'Quantity:')]</value>
      <webElementGuid>ba01b1bb-47ab-44c4-a720-bf9b4fe14760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
