<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Qty</name>
   <tag></tag>
   <elementGuidId>2133041d-d823-4995-9a7a-488fa4d0fa82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-dropdown-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='a-autoid-0-announce']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85be5466-68eb-479b-99b8-3179da82e2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-label</value>
      <webElementGuid>c0d2b2af-ef5f-4988-bd5f-6b92f06579dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qty:</value>
      <webElementGuid>5b529022-5dac-42ea-9b80-e6e92433069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0-announce&quot;)/span[@class=&quot;a-dropdown-label&quot;]</value>
      <webElementGuid>2634e854-24a3-4e74-b18f-196cf0fdd5e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0-announce']/span</value>
      <webElementGuid>e8c61d0a-b63e-49bb-96c5-4c9ab0f90973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>53f6955f-f6ac-461e-b960-ac0f972a2766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Qty:' or . = 'Qty:')]</value>
      <webElementGuid>92806f4b-79e0-426c-a036-42bcf20d02fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
