<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Quantity</name>
   <tag></tag>
   <elementGuidId>507def0a-200c-4819-937f-bbd388a8c39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-dropdown-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='a-autoid-0-announce']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7e10b1e-5407-4e11-aca4-8ed8bbb74857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-label</value>
      <webElementGuid>4970463f-2056-429d-99cf-d33c7f608446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quantity:</value>
      <webElementGuid>6e3c8d2d-de9f-467b-9b1a-7b7399e9fa2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0-announce&quot;)/span[@class=&quot;a-dropdown-label&quot;]</value>
      <webElementGuid>c997a762-4b87-4190-8869-8b410f8a0cd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0-announce']/span</value>
      <webElementGuid>76a31d2e-01d9-4b11-9279-442f39c69048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>80d803a4-7cc8-439b-8644-acfc01114472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Quantity:' or . = 'Quantity:')]</value>
      <webElementGuid>127e54dc-573b-412e-bd41-e8182de4204a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
