<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_AMAZON_SEARCH_001</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f7104571-51af-4777-a61b-e6914db64ce5</testSuiteGuid>
   <testCaseLink>
      <guid>3e630b0b-0cc5-4d2e-a844-718d366db5ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven Testing/TC_AMAZON_SEARCH_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c96b6444-545c-41cf-b3e4-88e7766997b5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Datadriven/TC_AMAZON_SEARCH_001</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c96b6444-545c-41cf-b3e4-88e7766997b5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>76b0d414-2e02-4fad-96f8-e531f096493b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c96b6444-545c-41cf-b3e4-88e7766997b5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>a2449a2f-6fea-4e99-a7b4-da94cc5fa6e1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
