<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_AMAZON_SEARCH_001</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a2bbe6ee-25dc-4f0d-92b0-aebb312f125b</testSuiteGuid>
   <testCaseLink>
      <guid>282f88c2-9eca-43b8-84a7-830c8b483942</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven Testing/TC_AMAZON_SEARCH_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>539bc93b-3a83-459c-a6a7-38eb8d0c8d84</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Datadriven/TC_AMAZON_SEARCH_001</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>539bc93b-3a83-459c-a6a7-38eb8d0c8d84</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>083ccbe0-822e-4ea8-b533-ae18ffed8347</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>539bc93b-3a83-459c-a6a7-38eb8d0c8d84</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>efaaa8b3-06b7-49b7-a72a-082bf1de3015</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
